---
repos:
  - repo: https://github.com/pre-commit/pre-commit.git
    rev: v1.20.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.4.0
    hooks:
      - id: check-yaml
      # Hooks able to fix small things.
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ".svg$|.po$"
      - id: fix-encoding-pragma
      # Hooks doing lightweight Python checks.
      - id: check-docstring-first
      - id: debug-statements
  - repo: https://github.com/asottile/reorder_python_imports.git
    rev: v1.8.0
    hooks:
      - id: reorder-python-imports
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args:
          # http://flake8.pycqa.org/en/latest/user/error-codes.html
          # https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes
          - --ignore=E402,E501,E722,F401,F841,W504
